name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify linter rules
        run: npx nx lint intertek

      - name: Run unit tests
        run: npx nx test intertek

      - name: Build production assets
        run: npx nx build intertek
